"""empty message

Revision ID: 466c97e665e7
Revises: 3108e2e3a6be
Create Date: 2023-03-28 23:20:32.915319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466c97e665e7'
down_revision = '3108e2e3a6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
