"""books table

Revision ID: 563b551bcde2
Revises: 099c785fbabd
Create Date: 2023-03-26 21:13:27.120791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563b551bcde2'
down_revision = '099c785fbabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=64), nullable=True),
    sa.Column('book_synopsis', sa.String(length=64), nullable=True),
    sa.Column('book_content', sa.String(length=64), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_book_content'), ['book_content'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_book_synopsis'), ['book_synopsis'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_book_title'), ['book_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_date_uploaded'), ['date_uploaded'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_date_uploaded'))
        batch_op.drop_index(batch_op.f('ix_book_book_title'))
        batch_op.drop_index(batch_op.f('ix_book_book_synopsis'))
        batch_op.drop_index(batch_op.f('ix_book_book_content'))

    op.drop_table('book')
    # ### end Alembic commands ###
