"""empty message

Revision ID: 0919032b9d80
Revises: ef2c6a32bc5a
Create Date: 2023-03-29 09:17:51.887991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0919032b9d80'
down_revision = 'ef2c6a32bc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('rendered_data', sa.Text(), nullable=False))
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.drop_column('rendered_data')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
