"""empty message

Revision ID: 1d10ff11eacf
Revises: 628bba2f28f0
Create Date: 2023-03-28 21:29:09.064676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d10ff11eacf'
down_revision = '628bba2f28f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_firstname', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_user_user_firtname')
        batch_op.drop_index('ix_user_user_lastname')
        batch_op.drop_column('user_firtname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_firtname', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_user_user_lastname', ['user_lastname'], unique=False)
        batch_op.create_index('ix_user_user_firtname', ['user_firtname'], unique=False)
        batch_op.drop_column('user_firstname')

    # ### end Alembic commands ###
