"""empty message

Revision ID: 3108e2e3a6be
Revises: 282e103eabbd
Create Date: 2023-03-28 22:09:53.632736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3108e2e3a6be'
down_revision = '282e103eabbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))
        batch_op.drop_column('book_synopsis')
        batch_op.drop_column('book_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_title', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('book_synopsis', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
